
# Project Information
site_name: LEAP Technical Documentation
site_url: https://leap-stc.github.io/
site_author: LEAP Data and Compute Team
site_description: The home for all technical documentation related to LEAP and LEAP-Pangeo

# Repository Information
repo_name: leap-stc.github.io
repo_url: https://github.com/leap-stc/leap-stc.github.io
docs_dir: docs

nav:
  - "index.md"
  - Introduction:
      - introduction/getting_started.md
      - introduction/what_is_the_hub.md
  - Data:
      - data/data_locations.md
      - data/data_lifecycle.md
      - data/data_catalog.md

  - Compute:
      - Hub Access:
          - Overview: compute/hub_access.md
          - Access via Browser: compute/hub_browser_access.md
          - Access VSCode inside Hub: compute/vscode_inside_hub.md
          - Access via VSCode: compute/vs_code_to_hub.md
      - compute/compute_scaling.md
      - compute/manage_software.md
      
  - Education / Outreach:
      - edu/classes.md
      - edu/bootcamps.md
  - Reference:
      - reference/file_formats.md
      - reference/rclone.md
      - reference/authentication.md
      - reference/infrastructure_details.md
      - reference/faqs.md
      

  - Support:
      - support/contact.md
      - support/signup_troubleshooting.md
      - support/hub_access_error.md
      - support/dask_killed_workers.md
      - support/hub_usage_alert.md

theme:
  language: en
  name: material
  logo: assets/LEAP_globe.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Veranda
    code: Roboto Mono

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - header.autohide 
    - search.suggest
    - search.share
    - toc.integrate

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://leap.columbia.edu/

plugins:
  - search
  - markdown-exec
  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - toc:
      permalink: true
